### PR TITLE
Project 3: Clone NYT article page

### PR DESCRIPTION
**Pull request by abongsjoel**
In this projet, we have cloned the NYT article page. We created a header element that is fixed on the page, we used CSS grid to position the items in the header.  We made use of HTML5 semantic elements such as section, article, and figure in various parts of the page. We created an aside element for the Editor's picks and used positioning to position it to the side of the page. We made use of flexbox to position icons in the article. We also made use of CSS grid for The Theory of inflation section.

### CODE REVIEW

**Review by Srjnnnn — CHANGES_REQUESTED** [review]
### ### Status: Changes Required :recycle: :stop_sign: 

Hello team! You've done a marvelous job! :100: 
- You've used flex and grid professionally! :+1: 
- Your page looks identical to the original page :+1: 
- You've used aside tag and semantic HTML. :+1: 

However, there are small issues I'd like to mention:
- [ ] Kindly make the New York Times logo a link.
- [ ] Just found one CSS repetition from line 228 to 234. Kindly put them together.
- [ ] Please check for more repetition as above.

- [ ] Optional: Your outline structure is not the same as the page. If you'd like to investigate more and improve your structure. you can use [this link](https://gsnedders.html5.org/outliner/).

Again great work! :100: 
Please, fix those issues and submit them for another review.
If there is confusion about the review, you can reach me via Slack. :100: 
Eyüp Sercan UYGUR

**Review by Srjnnnn — CHANGES_REQUESTED** [review]
### Status: Changes Required :recycle: :stop_sign: 

Hello team again. :smiley: 
I know these issues were not big issues and I also don't want to make you waste your time in here much, but still, there is an issue.

- [ ] Right now stylelint is giving an error. Please fix this. There are ordering issues.

You've changed the logo to a link :+1: 
You've grouped the repetitions :+1: 

Please fix this only issue and submit for a re-review again.

-----Edit-----
If you can use more descriptive commit messages, eg. group repetitive selectors, fix linter... That would be better :smiley_cat: 

If there is confusion about the review, please reach me via Slack.
Eyüp Sercan UYGUR

**Review by ioilmio — CHANGES_REQUESTED** [review]
## Hey Team @abongsjoel @leolpaz 
### Great job on fixing all previous requirements 👍🏼 

# The page looks the same as the original... amazing job!
### But your project lacks just one mandatory feature:
## local linters.

you can find the documentation to add them to your project [here](https://github.com/microverseinc/linters-config/tree/master/html-css)

## Please add them and your project will be approved.

# Thank you!

### Even if your linters are working on GitHub and pass all checks I can't approve the project without them included in your root folder 

### P.S. I wanted to approve but I can't 😞
If you included these from the beginning next time, it will be more easy for you to fix style issues and move forward

**Review by mahmoud717 — APPROVED** [review]
## Project approved #
good job guys, you can go ahead and merge this pull request

**Pull request merged**
